# Generated by Django 5.1.2 on 2024-11-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_auto_20241128_0436"),
    ]

    operations = []
