# Generated by Django 5.1.2 on 2024-11-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_auto_20241128_0442"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="individual_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="user_management.permission"
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                ],
                default="view",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="permission",
            name="resource",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("role", "Role"),
                    ("department", "Department"),
                ],
                default="user",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="user_management.permission"
            ),
        ),
    ]
