# Generated by Django 5.1.2 on 2024-11-27 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_management",
            "0004_customuser_individual_permissions_permission_action_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(model_name="permission", name="name",),
        migrations.AlterField(
            model_name="permission",
            name="resource",
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name="permission",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="user_management.module",
            ),
        ),
    ]
