# Generated by Django 5.1.2 on 2024-11-28 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0005_module_remove_permission_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission", options={"ordering": ["module", "resource", "action"]},
        ),
        migrations.AddField(
            model_name="permission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="permission",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="permission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="permission",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("execute", "Execute"),
                ],
                default="view",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="permission", unique_together={("module", "resource", "action")},
        ),
    ]
