# Generated by Django 5.1.2 on 2024-11-27 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyeartransition",
            name="processed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="academicyeartransition",
            name="to_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transitions_to",
                to="core.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="criteria",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="criteria",
                to="core.board",
            ),
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.academicyear"
            ),
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verified_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.department"
            ),
        ),
        migrations.AddField(
            model_name="submissiondata",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_rows",
                to="core.datasubmission",
            ),
        ),
        migrations.AddField(
            model_name="submissionhistory",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submissionhistory",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="core.datasubmission",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="criteria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="core.criteria",
            ),
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.template"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicyeartransition", unique_together={("from_year", "to_year")},
        ),
        migrations.AlterUniqueTogether(
            name="criteria", unique_together={("board", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="submissiondata",
            unique_together={("submission", "section_index", "row_number")},
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(fields=["code"], name="core_templa_code_c8f349_idx"),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["created_at"], name="core_templa_created_20ebd2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="template", unique_together={("criteria", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="datasubmission",
            unique_together={("template", "department", "academic_year")},
        ),
    ]
