# Generated by Django 5.1.2 on 2024-11-24 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="datasubmission", name="board",),
        migrations.AlterUniqueTogether(
            name="template", unique_together={("criteria", "code")},
        ),
        migrations.AddField(
            model_name="criteria",
            name="board",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="criteria",
                to="core.board",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="template",
            name="criteria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="core.criteria",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="criteria", unique_together={("board", "number")},
        ),
        migrations.RemoveField(model_name="template", name="board",),
    ]
