# Generated by Django 5.1.2 on 2024-11-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_template_column_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='columns',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='template',
            name='column_groups',
        ),
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
        migrations.RemoveField(
            model_name='template',
            name='headers',
        ),
        migrations.AlterField(
            model_name='template',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
