# Generated by Django 5.1.2 on 2024-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_datasubmission_board_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="criteria", name="number", field=models.IntegerField(),
        ),
    ]
