# Generated by Django 5.1.2 on 2024-12-01 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("user_management", "0003_customuser_first_name_customuser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasubmission",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="user_management.department",
            ),
        ),
    ]
