# Generated by Django 5.1.2 on 2024-11-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_columns_template_metadata_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={},
        ),
    ]
