# Generated by Django 5.1.2 on 2024-12-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_criteria_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="code",
            field=models.CharField(
                help_text="Template code (e.g., '2.1.1')", max_length=20
            ),
        ),
    ]
