# Generated by Django 5.1.2 on 2024-11-18 19:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_template_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicyear", options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="datasubmission",
            options={"ordering": ["-academic_year__start_date", "-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="submissiondata",
            options={"ordering": ["section_index", "row_number"]},
        ),
        migrations.AlterUniqueTogether(name="datasubmission", unique_together=set(),),
        migrations.AlterUniqueTogether(name="submissiondata", unique_together=set(),),
        migrations.RemoveField(model_name="academicyear", name="year",),
        migrations.AddField(
            model_name="academicyear",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicyear",
            name="transition_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="transition_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datasubmission",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="submissiondata",
            name="section_index",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="datasubmission",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.academicyear"
            ),
        ),
        migrations.AlterField(
            model_name="datasubmission",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.department"
            ),
        ),
        migrations.AlterField(
            model_name="datasubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="datasubmission",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="datasubmission",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="datasubmission",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.template"
            ),
        ),
        migrations.AlterField(
            model_name="datasubmission",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="verified_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datasubmission",
            unique_together={("template", "department", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="submissiondata",
            unique_together={("submission", "section_index", "row_number")},
        ),
        migrations.CreateModel(
            name="AcademicYearTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_log", models.TextField(blank=True, null=True)),
                (
                    "from_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions_from",
                        to="core.academicyear",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transitions_to",
                        to="core.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "unique_together": {("from_year", "to_year")},
            },
        ),
    ]
