# Generated by Django 5.1.2 on 2024-11-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_academicyear_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="template", options={"ordering": ["code"]},),
        migrations.AlterField(
            model_name="template",
            name="code",
            field=models.CharField(
                help_text="Template code (e.g., '2.1.1')", max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="metadata",
            field=models.JSONField(
                help_text="Template structure including sections, headers, and columns"
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="name",
            field=models.CharField(help_text="Template name/title", max_length=500),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(fields=["code"], name="core_templa_code_c8f349_idx"),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["created_at"], name="core_templa_created_20ebd2_idx"
            ),
        ),
    ]
