# Generated by Django 5.1.2 on 2024-11-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_submissionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissionhistory",
            name="new_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submissionhistory",
            name="previous_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
