# Generated by Django 5.1.2 on 2024-11-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_submissionhistory_new_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='datasubmission',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.board'),
        ),
        migrations.AddField(
            model_name='template',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.board'),
        ),
    ]
