# Generated by Django 5.1.2 on 2024-11-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_boards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boards',
            new_name='Board',
        ),
    ]
