# Generated by Django 5.1.2 on 2024-11-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_board_datasubmission_board_template_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Criteria',
                'ordering': ['order', 'number'],
            },
        ),
        migrations.AlterModelOptions(
            name='datasubmission',
            options={'ordering': ['-academic_year__start_date', '-updated_at'], 'permissions': [('can_verify_submission', 'Can verify submission'), ('can_view_all_submissions', 'Can view all submissions')]},
        ),
        migrations.AlterField(
            model_name='datasubmission',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.board'),
        ),
        migrations.AlterField(
            model_name='template',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.board'),
        ),
        migrations.AddField(
            model_name='template',
            name='criteria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='core.criteria'),
        ),
    ]
