# Generated by Django 5.1.2 on 2024-11-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_boards_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubmission',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.board'),
        ),
        migrations.AddField(
            model_name='template',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.board'),
        ),
    ]
