# Generated by Django 5.1.2 on 2024-11-24 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_criteria_alter_datasubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasubmission',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.board'),
        ),
        migrations.AlterField(
            model_name='template',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.board'),
        ),
    ]
