# Generated by Django 5.1.2 on 2024-11-24 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_datasubmission_board_alter_template_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasubmission',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.board'),
        ),
        migrations.AlterField(
            model_name='template',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.board'),
        ),
    ]
