# Generated by Django 5.1.2 on 2024-11-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_datasubmission_board_alter_template_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasubmission',
            name='board',
        ),
        migrations.RemoveField(
            model_name='template',
            name='board',
        ),
    ]
