# Generated by Django 5.1.2 on 2024-11-24 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_datasubmission_board_remove_template_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasubmission',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.board'),
        ),
        migrations.AddField(
            model_name='template',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.board'),
        ),
    ]
