# Generated by Django 5.1.2 on 2024-10-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naacfile',
            name='data',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='naacfile',
            name='structure',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='naacfile',
            name='subsection',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
